# Generated by Django 2.1 on 2019-05-04 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='idate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
