# Generated by Django 2.1 on 2019-05-14 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
