# Generated by Django 2.1 on 2019-05-06 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0002_auto_20190504_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='uid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='libadmin.Luser'),
        ),
    ]
