# Generated by Django 2.1 on 2019-05-15 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0003_map'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Map',
        ),
    ]
