# Generated by Django 2.1 on 2019-05-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0004_book_rcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='luser',
            name='isactivated',
            field=models.BooleanField(default=False),
        ),
    ]
