# Generated by Django 2.1 on 2019-05-04 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('libadmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Syllabus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('textbook', models.CharField(max_length=100)),
                ('syllabus', models.CharField(max_length=1500)),
                ('ebooks', models.CharField(max_length=1500, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libadmin.Dept')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='syllabus',
            unique_together={('dept', 'sem')},
        ),
    ]
