# Generated by Django 2.1 on 2019-05-14 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0001_initial'),
        ('libsyllabus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('cf', models.FileField(upload_to='media/')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libadmin.Dept')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsyllabus.Subject'),
        ),
        migrations.AddField(
            model_name='coursefile',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libsyllabus.Subject'),
        ),
        migrations.AlterUniqueTogether(
            name='coursefile',
            unique_together={('dept', 'sem', 'subject')},
        ),
    ]
