# Generated by Django 2.1 on 2019-05-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsyllabus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='ebooks',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
