# Generated by Django 2.1 on 2019-05-15 06:34

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('libsyllabus', '0002_auto_20190514_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursefile',
            name='cf',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='docs'),
        ),
    ]
