# Generated by Django 2.1 on 2019-05-05 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0002_auto_20190504_2218'),
        ('libsyllabus', '0002_auto_20190504_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Textbooks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('textbook', models.CharField(max_length=100)),
                ('ebooks', models.CharField(blank=True, max_length=1500, null=True)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='libadmin.Dept')),
            ],
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='ebooks',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='textbook',
        ),
        migrations.AlterUniqueTogether(
            name='textbooks',
            unique_together={('dept', 'sem')},
        ),
    ]
