# Generated by Django 2.1 on 2019-05-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsyllabus', '0003_auto_20190505_0617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus',
            field=models.FileField(upload_to=''),
        ),
    ]
