# Generated by Django 2.1 on 2019-05-15 07:57

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('libsyllabus', '0003_auto_20190515_1204'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coursefile',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='coursefile',
            name='dept',
        ),
        migrations.RemoveField(
            model_name='coursefile',
            name='subject',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='coursefile',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='docs'),
        ),
        migrations.AlterField(
            model_name='syllabus',
            name='syllabus',
            field=models.FileField(null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='docs'),
        ),
        migrations.DeleteModel(
            name='CourseFile',
        ),
    ]
