# Generated by Django 2.1 on 2019-05-05 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libadmin', '0002_auto_20190504_2218'),
        ('libsyllabus', '0004_auto_20190505_0628'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='textbooks',
            unique_together={('dept', 'sem', 'subject')},
        ),
    ]
